/// All translated UI copy, keyed by language code then by string key.
///
/// Scope note: this covers the app's chrome -- navigation, buttons, empty
/// states, instructions -- not the disease catalog itself. The catalog's
/// descriptions and treatment steps are agronomic/scientific content
/// authored in English for accuracy; translating ~40 diseases' worth of
/// technical guidance into nine languages without an agronomist reviewing
/// each one risked giving a farmer subtly wrong advice, which is worse than
/// an English paragraph in an otherwise-local interface. [t] falls back to
/// English for any key a language hasn't got, so nothing ever renders blank.
class AppStrings {
  AppStrings._();

  static String t(String languageCode, String key) {
    return _all[languageCode]?[key] ?? _en[key] ?? key;
  }

  static const Map<String, Map<String, String>> _all = {
    'en': _en,
    'hi': _hi,
    'mr': _mr,
    'te': _te,
    'ta': _ta,
    'bn': _bn,
    'gu': _gu,
    'kn': _kn,
    'pa': _pa,
  };

  static const Map<String, String> _en = {
    'appTagline': 'Point your camera at a leaf. Get a diagnosis in seconds — no signal needed.',
    'loadingModel': 'Loading the on-device model…',
    'navHome': 'Home',
    'navHistory': 'History',
    'diseaseGuideTitle': 'Disease guide',
    'diseaseGuideSubtitle': 'Browse what LeafGuard can identify',
    'recentScans': 'Recent scans',
    'noScansYet': 'No scans yet',
    'noScansHint': 'Tap the camera button below to scan your first leaf.',
    'cropTomato': 'Tomato',
    'cropPotato': 'Potato',
    'cropCorn': 'Corn',
    'scanInstruction': 'Center the leaf, fill the frame, avoid shadows',
    'cameraPermissionError': "Couldn't access the camera. Check camera permissions in Settings.",
    'captureError': "Couldn't capture that photo. Try again.",
    'galleryError': "Couldn't open that photo. Try again.",
    'galleryLabel': 'Gallery',
    'cameraLabel': 'Camera',
    'goBack': 'Go back',
    'analyzing': 'Analyzing your leaf…',
    'runningOnDevice': 'Running entirely on this device',
    'confidence': 'Confidence',
    'keepItThatWay': 'Keep it that way',
    'scanAnother': 'Scan another leaf',
    'tabOrganic': 'Organic',
    'tabChemical': 'Chemical',
    'tabPrevention': 'Prevention',
    'errorGeneric': 'Something went wrong.',
    'tryAgain': 'Try again',
    'severityHealthy': 'Healthy',
    'severityMild': 'Mild',
    'severitySevere': 'Needs attention',
    'historyTitle': 'History',
    'historySubtitle': "Every leaf you've scanned, stored on this device.",
    'nothingScannedYet': 'Nothing scanned yet',
    'historyEmptyHint': 'Your scan history will show up here.',
    'welcomeBack': 'Welcome back',
    'signInSubtitle': 'Sign in to sync your scan history across devices.',
    'emailHint': 'Email',
    'passwordHint': 'Password',
    'signIn': 'Sign in',
    'noAccountSignUp': "Don't have an account? Sign up",
    'continueWithoutAccount': 'Continue without an account',
    'createAccount': 'Create account',
    'signupIntro':
        'Your scans stay on this device either way — an account just lets you sync and recover them.',
    'organicTreatment': 'Organic treatment',
    'chemicalTreatment': 'Chemical treatment',
    'preventionTips': 'Prevention',
    'chooseLanguage': 'Choose your language',
    'initErrorTitle': "Couldn't start LeafGuard",
    'initErrorBody':
        'Make sure the model files are set up correctly. See the app README for setup steps.',
    'scanLeaf': 'Scan a leaf',
    'diagnoseNow': 'Diagnose now',

    // Settings
    'settingsTitle': 'Settings',
    'settingsGeneral': 'General',
    'settingsAccount': 'Account',
    'changeLanguage': 'Language',
    'yourLocation': 'Your location',
    'locationNotSet': 'Not set',
    'signedIn': 'Signed in',
    'notSignedInHint': 'Sign in to sync your scan history across devices.',
    'signOut': 'Sign out',
    'appVersionLabel': 'LeafGuard v1.0',

    // First-run setup
    'setupWelcomeTitle': 'Welcome to LeafGuard',
    'setupLanguagePrompt': 'Choose the language you\u2019d like to use.',
    'setupLocationTitle': 'Where are you farming?',
    'setupLocationPrompt': 'This helps tailor advice to your region. You can skip this and add it later.',
    'setupLocationHint': 'Village or city, state',
    'continueLabel': 'Continue',
    'skipForNow': 'Skip for now',

    // AI assistant
    'aiAssistantTitle': 'AI Assistant',
    'aiNotConfigured': 'The AI assistant needs a backend connection to work. Ask the app\u2019s developer to configure Supabase and the ai-chat function.',
    'askAiCardTitle': 'Ask the AI assistant',
    'askAiCardSubtitle': 'Get answers about any crop issue, in your language',
    'askAiAboutThis': 'Ask AI about this',
    'chatWelcomeMessage': 'Hi! I\u2019m LeafGuard\u2019s AI assistant. Ask me anything about crop diseases, treatments, or what you\u2019re seeing on your plants.',
    'chatSeedIssueIntro': 'I can see your scan found an issue on',
    'chatSeedHealthyIntro': 'Good news — your scan came back healthy for',
    'chatSeedPrompt': 'Ask me anything about it — causes, treatment options, or how to stop it spreading.',
    'chatInputHint': 'Type your question…',
    'chatErrorGeneric': 'Couldn\u2019t reach the assistant. Check your connection and try again.',
    'chatQuickCause': 'What caused this?',
    'chatQuickOrganicFirst': 'What\u2019s the safest organic fix?',
    'chatQuickSpreadRisk': 'Will it spread to other plants?',
    'chatQuickKeepHealthy': 'How do I keep it this healthy?',
    'chatQuickPreventFuture': 'How do I prevent future issues?',
  };

  static const Map<String, String> _hi = {
    'appTagline': 'अपने कैमरे को पत्ते पर रखें। कुछ ही सेकंड में जांच पाएं — इंटरनेट की ज़रूरत नहीं।',
    'loadingModel': 'मॉडल लोड हो रहा है…',
    'navHome': 'होम',
    'navHistory': 'इतिहास',
    'diseaseGuideTitle': 'रोग गाइड',
    'diseaseGuideSubtitle': 'लीफगार्ड जिन रोगों को पहचान सकता है, उन्हें देखें',
    'recentScans': 'हाल की स्कैन',
    'noScansYet': 'अभी कोई स्कैन नहीं',
    'noScansHint': 'अपना पहला पत्ता स्कैन करने के लिए नीचे कैमरा बटन दबाएं।',
    'cropTomato': 'टमाटर',
    'cropPotato': 'आलू',
    'cropCorn': 'मक्का',
    'scanInstruction': 'पत्ते को बीच में रखें, फ्रेम भरें, छाया से बचें',
    'cameraPermissionError': 'कैमरे तक पहुंच नहीं हो पाई। सेटिंग्स में कैमरा अनुमति जांचें।',
    'captureError': 'फोटो नहीं ली जा सकी। फिर से कोशिश करें।',
    'galleryError': 'फोटो नहीं खुल सकी। फिर से कोशिश करें।',
    'galleryLabel': 'गैलरी',
    'cameraLabel': 'कैमरा',
    'goBack': 'वापस जाएं',
    'analyzing': 'आपके पत्ते की जांच हो रही है…',
    'runningOnDevice': 'यह पूरी तरह आपके फोन पर ही चल रहा है',
    'confidence': 'विश्वसनीयता',
    'keepItThatWay': 'ऐसे ही बनाए रखें',
    'scanAnother': 'एक और पत्ता स्कैन करें',
    'tabOrganic': 'जैविक',
    'tabChemical': 'रासायनिक',
    'tabPrevention': 'बचाव',
    'errorGeneric': 'कुछ गड़बड़ हो गई।',
    'tryAgain': 'फिर से कोशिश करें',
    'severityHealthy': 'स्वस्थ',
    'severityMild': 'हल्का',
    'severitySevere': 'ध्यान देने की जरूरत',
    'historyTitle': 'इतिहास',
    'historySubtitle': 'आपके सभी स्कैन किए गए पत्ते, इस डिवाइस पर सुरक्षित।',
    'nothingScannedYet': 'अभी तक कुछ स्कैन नहीं हुआ',
    'historyEmptyHint': 'आपका स्कैन इतिहास यहां दिखेगा।',
    'welcomeBack': 'वापसी पर स्वागत है',
    'signInSubtitle': 'अपने स्कैन इतिहास को सभी डिवाइस पर सिंक करने के लिए साइन इन करें।',
    'emailHint': 'ईमेल',
    'passwordHint': 'पासवर्ड',
    'signIn': 'साइन इन करें',
    'noAccountSignUp': 'खाता नहीं है? साइन अप करें',
    'continueWithoutAccount': 'बिना खाते के जारी रखें',
    'createAccount': 'खाता बनाएं',
    'signupIntro':
        'आपके स्कैन वैसे भी इसी डिवाइस पर सुरक्षित रहते हैं — खाता बनाने से आप उन्हें सिंक और रिकवर कर सकते हैं।',
    'organicTreatment': 'जैविक उपचार',
    'chemicalTreatment': 'रासायनिक उपचार',
    'preventionTips': 'बचाव के उपाय',
    'chooseLanguage': 'अपनी भाषा चुनें',
    'initErrorTitle': 'लीफगार्ड शुरू नहीं हो सका',
    'initErrorBody': 'सुनिश्चित करें कि मॉडल फ़ाइलें सही तरीके से सेट हैं। सेटअप चरणों के लिए ऐप की README देखें।',
    'scanLeaf': 'पत्ता स्कैन करें',
    'diagnoseNow': 'अभी जांचें',

    'settingsTitle': 'सेटिंग्स',
    'settingsGeneral': 'सामान्य',
    'settingsAccount': 'खाता',
    'changeLanguage': 'भाषा',
    'yourLocation': 'आपका स्थान',
    'locationNotSet': 'सेट नहीं है',
    'signedIn': 'साइन इन है',
    'notSignedInHint': 'अपने सभी डिवाइस पर स्कैन इतिहास सिंक करने के लिए साइन इन करें।',
    'signOut': 'साइन आउट करें',
    'appVersionLabel': 'लीफगार्ड v1.0',

    'setupWelcomeTitle': 'लीफगार्ड में आपका स्वागत है',
    'setupLanguagePrompt': 'वह भाषा चुनें जिसका आप उपयोग करना चाहते हैं।',
    'setupLocationTitle': 'आप कहाँ खेती करते हैं?',
    'setupLocationPrompt': 'इससे आपके क्षेत्र के अनुसार सलाह देने में मदद मिलती है। आप इसे छोड़ भी सकते हैं और बाद में जोड़ सकते हैं।',
    'setupLocationHint': 'गांव या शहर, राज्य',
    'continueLabel': 'जारी रखें',
    'skipForNow': 'अभी के लिए छोड़ें',

    'aiAssistantTitle': 'एआई सहायक',
    'aiNotConfigured': 'एआई सहायक को काम करने के लिए बैकएंड कनेक्शन की आवश्यकता है। ऐप डेवलपर से Supabase और ai-chat फ़ंक्शन सेट करने के लिए कहें।',
    'askAiCardTitle': 'एआई सहायक से पूछें',
    'askAiCardSubtitle': 'अपनी भाषा में किसी भी फसल समस्या के बारे में जवाब पाएं',
    'askAiAboutThis': 'इसके बारे में एआई से पूछें',
    'chatWelcomeMessage': 'नमस्ते! मैं लीफगार्ड का एआई सहायक हूं। फसल रोगों, उपचारों या आपके पौधों पर जो दिख रहा है, उसके बारे में मुझसे कुछ भी पूछें।',
    'chatSeedIssueIntro': 'मैं देख सकता हूं कि आपके स्कैन में समस्या मिली है',
    'chatSeedHealthyIntro': 'अच्छी खबर — आपका स्कैन स्वस्थ पाया गया',
    'chatSeedPrompt': 'इसके बारे में मुझसे कुछ भी पूछें — कारण, उपचार के विकल्प, या इसे फैलने से कैसे रोकें।',
    'chatInputHint': 'अपना सवाल लिखें…',
    'chatErrorGeneric': 'सहायक तक नहीं पहुंच सका। अपना कनेक्शन जांचें और फिर से कोशिश करें।',
    'chatQuickCause': 'इसका कारण क्या है?',
    'chatQuickOrganicFirst': 'सबसे सुरक्षित जैविक उपाय क्या है?',
    'chatQuickSpreadRisk': 'क्या यह अन्य पौधों में फैलेगा?',
    'chatQuickKeepHealthy': 'मैं इसे ऐसे ही स्वस्थ कैसे रखूं?',
    'chatQuickPreventFuture': 'भविष्य की समस्याओं को कैसे रोकूं?',
  };

  static const Map<String, String> _mr = {
    'appTagline': 'तुमचा कॅमेरा पानावर धरा. काही सेकंदात निदान मिळवा — इंटरनेटची गरज नाही.',
    'loadingModel': 'मॉडेल लोड होत आहे…',
    'navHome': 'मुख्यपृष्ठ',
    'navHistory': 'इतिहास',
    'diseaseGuideTitle': 'रोग मार्गदर्शक',
    'diseaseGuideSubtitle': 'लीफगार्ड कोणते रोग ओळखू शकते ते पहा',
    'recentScans': 'अलीकडील स्कॅन',
    'noScansYet': 'अजून कोणतेही स्कॅन नाही',
    'noScansHint': 'पहिले पान स्कॅन करण्यासाठी खालील कॅमेरा बटण दाबा.',
    'cropTomato': 'टोमॅटो',
    'cropPotato': 'बटाटा',
    'cropCorn': 'मका',
    'scanInstruction': 'पान मध्यभागी ठेवा, फ्रेम भरा, सावली टाळा',
    'cameraPermissionError': 'कॅमेऱ्यात प्रवेश मिळाला नाही. सेटिंग्जमध्ये कॅमेरा परवानगी तपासा.',
    'captureError': 'फोटो घेता आला नाही. पुन्हा प्रयत्न करा.',
    'galleryError': 'फोटो उघडता आला नाही. पुन्हा प्रयत्न करा.',
    'galleryLabel': 'गॅलरी',
    'cameraLabel': 'कॅमेरा',
    'goBack': 'मागे जा',
    'analyzing': 'तुमच्या पानाची तपासणी सुरू आहे…',
    'runningOnDevice': 'हे पूर्णपणे तुमच्या फोनवरच चालते',
    'confidence': 'विश्वासार्हता',
    'keepItThatWay': 'असेच सुरू ठेवा',
    'scanAnother': 'आणखी एक पान स्कॅन करा',
    'tabOrganic': 'सेंद्रिय',
    'tabChemical': 'रासायनिक',
    'tabPrevention': 'प्रतिबंध',
    'errorGeneric': 'काहीतरी चूक झाली.',
    'tryAgain': 'पुन्हा प्रयत्न करा',
    'severityHealthy': 'निरोगी',
    'severityMild': 'सौम्य',
    'severitySevere': 'लक्ष देण्याची गरज',
    'historyTitle': 'इतिहास',
    'historySubtitle': 'तुम्ही स्कॅन केलेली सर्व पाने, या डिव्हाइसवर साठवलेली.',
    'nothingScannedYet': 'अजून काहीही स्कॅन केलेले नाही',
    'historyEmptyHint': 'तुमचा स्कॅन इतिहास इथे दिसेल.',
    'welcomeBack': 'पुन्हा स्वागत आहे',
    'signInSubtitle': 'सर्व डिव्हाइसवर तुमचा स्कॅन इतिहास सिंक करण्यासाठी साइन इन करा.',
    'emailHint': 'ईमेल',
    'passwordHint': 'पासवर्ड',
    'signIn': 'साइन इन करा',
    'noAccountSignUp': 'खाते नाही? साइन अप करा',
    'continueWithoutAccount': 'खात्याशिवाय पुढे जा',
    'createAccount': 'खाते तयार करा',
    'signupIntro':
        'तुमचे स्कॅन कोणत्याही परिस्थितीत या डिव्हाइसवरच राहतात — खाते फक्त सिंक आणि रिकव्हरीसाठी उपयोगी आहे.',
    'organicTreatment': 'सेंद्रिय उपचार',
    'chemicalTreatment': 'रासायनिक उपचार',
    'preventionTips': 'प्रतिबंधात्मक उपाय',
    'chooseLanguage': 'तुमची भाषा निवडा',
    'initErrorTitle': 'लीफगार्ड सुरू होऊ शकले नाही',
    'initErrorBody': 'मॉडेल फाइल्स योग्यरित्या सेट केल्या आहेत याची खात्री करा. सेटअप पायऱ्यांसाठी ॲपचे README पहा.',
    'scanLeaf': 'पान स्कॅन करा',
    'diagnoseNow': 'आत्ता तपासा',

    'settingsTitle': 'सेटिंग्ज',
    'settingsGeneral': 'सामान्य',
    'settingsAccount': 'खाते',
    'changeLanguage': 'भाषा',
    'yourLocation': 'तुमचे स्थान',
    'locationNotSet': 'सेट केलेले नाही',
    'signedIn': 'साइन इन आहे',
    'notSignedInHint': 'सर्व डिव्हाइसवर तुमचा स्कॅन इतिहास सिंक करण्यासाठी साइन इन करा.',
    'signOut': 'साइन आउट करा',
    'appVersionLabel': 'लीफगार्ड v1.0',

    'setupWelcomeTitle': 'लीफगार्डमध्ये आपले स्वागत आहे',
    'setupLanguagePrompt': 'तुम्हाला वापरायची असलेली भाषा निवडा.',
    'setupLocationTitle': 'तुम्ही कुठे शेती करता?',
    'setupLocationPrompt': 'यामुळे तुमच्या प्रदेशानुसार सल्ला देण्यात मदत होते. तुम्ही हे वगळून नंतर जोडू शकता.',
    'setupLocationHint': 'गाव किंवा शहर, राज्य',
    'continueLabel': 'पुढे चला',
    'skipForNow': 'आत्तासाठी वगळा',

    'aiAssistantTitle': 'एआय सहाय्यक',
    'aiNotConfigured': 'एआय सहाय्यकाला काम करण्यासाठी बॅकएंड कनेक्शनची आवश्यकता आहे. अ‍ॅप डेव्हलपरला Supabase आणि ai-chat फंक्शन सेट करण्यास सांगा.',
    'askAiCardTitle': 'एआय सहाय्यकाला विचारा',
    'askAiCardSubtitle': 'तुमच्या भाषेत कोणत्याही पीक समस्येबद्दल उत्तरे मिळवा',
    'askAiAboutThis': 'याबद्दल एआयला विचारा',
    'chatWelcomeMessage': 'नमस्कार! मी लीफगार्डचा एआय सहाय्यक आहे. पीक रोग, उपचार किंवा तुमच्या रोपांवर काय दिसत आहे याबद्दल मला काहीही विचारा.',
    'chatSeedIssueIntro': 'मला दिसतंय की तुमच्या स्कॅनमध्ये समस्या आढळली आहे',
    'chatSeedHealthyIntro': 'चांगली बातमी — तुमचा स्कॅन निरोगी आढळला',
    'chatSeedPrompt': 'याबद्दल मला काहीही विचारा — कारणे, उपचार पर्याय, किंवा ते पसरण्यापासून कसे थांबवायचे.',
    'chatInputHint': 'तुमचा प्रश्न टाइप करा…',
    'chatErrorGeneric': 'सहाय्यकापर्यंत पोहोचता आले नाही. तुमचे कनेक्शन तपासा आणि पुन्हा प्रयत्न करा.',
    'chatQuickCause': 'याचे कारण काय आहे?',
    'chatQuickOrganicFirst': 'सर्वात सुरक्षित सेंद्रिय उपाय कोणता आहे?',
    'chatQuickSpreadRisk': 'हे इतर रोपांमध्ये पसरेल का?',
    'chatQuickKeepHealthy': 'मी हे असेच निरोगी कसे ठेवू?',
    'chatQuickPreventFuture': 'भविष्यातील समस्या कशा टाळू?',
  };

  static const Map<String, String> _te = {
    'appTagline': 'మీ కెమెరాను ఆకుపై పెట్టండి. సెకన్లలో నిర్ధారణ పొందండి — సిగ్నల్ అవసరం లేదు.',
    'loadingModel': 'మోడల్ లోడ్ అవుతోంది…',
    'navHome': 'హోమ్',
    'navHistory': 'చరిత్ర',
    'diseaseGuideTitle': 'వ్యాధి గైడ్',
    'diseaseGuideSubtitle': 'లీఫ్‌గార్డ్ గుర్తించగల వ్యాధులను చూడండి',
    'recentScans': 'ఇటీవలి స్కాన్‌లు',
    'noScansYet': 'ఇంకా స్కాన్‌లు లేవు',
    'noScansHint': 'మీ మొదటి ఆకును స్కాన్ చేయడానికి కింద ఉన్న కెమెరా బటన్ నొక్కండి.',
    'cropTomato': 'టమాటా',
    'cropPotato': 'బంగాళదుంప',
    'cropCorn': 'మొక్కజొన్న',
    'scanInstruction': 'ఆకును మధ్యలో ఉంచండి, ఫ్రేమ్ నింపండి, నీడలు నివారించండి',
    'cameraPermissionError': 'కెమెరాను యాక్సెస్ చేయలేకపోయాం. సెట్టింగ్‌లలో కెమెరా అనుమతిని తనిఖీ చేయండి.',
    'captureError': 'ఆ ఫోటో తీయలేకపోయాం. మళ్ళీ ప్రయత్నించండి.',
    'galleryError': 'ఆ ఫోటో తెరవలేకపోయాం. మళ్ళీ ప్రయత్నించండి.',
    'galleryLabel': 'గ్యాలరీ',
    'cameraLabel': 'కెమెరా',
    'goBack': 'వెనక్కి వెళ్ళండి',
    'analyzing': 'మీ ఆకును పరిశీలిస్తోంది…',
    'runningOnDevice': 'ఇది పూర్తిగా మీ ఫోన్‌లోనే జరుగుతుంది',
    'confidence': 'నమ్మకత్వం',
    'keepItThatWay': 'ఇలాగే కొనసాగించండి',
    'scanAnother': 'మరో ఆకును స్కాన్ చేయండి',
    'tabOrganic': 'సేంద్రియ',
    'tabChemical': 'రసాయనిక',
    'tabPrevention': 'నివారణ',
    'errorGeneric': 'ఏదో తప్పు జరిగింది.',
    'tryAgain': 'మళ్ళీ ప్రయత్నించండి',
    'severityHealthy': 'ఆరోగ్యంగా ఉంది',
    'severityMild': 'తేలికపాటి',
    'severitySevere': 'శ్రద్ధ అవసరం',
    'historyTitle': 'చరిత్ర',
    'historySubtitle': 'మీరు స్కాన్ చేసిన ప్రతి ఆకు, ఈ పరికరంలో నిల్వ చేయబడింది.',
    'nothingScannedYet': 'ఇంకా ఏమీ స్కాన్ చేయలేదు',
    'historyEmptyHint': 'మీ స్కాన్ చరిత్ర ఇక్కడ కనిపిస్తుంది.',
    'welcomeBack': 'తిరిగి స్వాగతం',
    'signInSubtitle': 'అన్ని పరికరాల్లో మీ స్కాన్ చరిత్రను సింక్ చేయడానికి సైన్ ఇన్ చేయండి.',
    'emailHint': 'ఇమెయిల్',
    'passwordHint': 'పాస్‌వర్డ్',
    'signIn': 'సైన్ ఇన్ చేయండి',
    'noAccountSignUp': 'ఖాతా లేదా? సైన్ అప్ చేయండి',
    'continueWithoutAccount': 'ఖాతా లేకుండా కొనసాగించండి',
    'createAccount': 'ఖాతా సృష్టించండి',
    'signupIntro':
        'మీ స్కాన్‌లు ఏ విధంగానైనా ఈ పరికరంలోనే ఉంటాయి — ఖాతా వాటిని సింక్ చేసి తిరిగి పొందడానికి మాత్రమే సహాయపడుతుంది.',
    'organicTreatment': 'సేంద్రియ చికిత్స',
    'chemicalTreatment': 'రసాయనిక చికిత్స',
    'preventionTips': 'నివారణ చిట్కాలు',
    'chooseLanguage': 'మీ భాషను ఎంచుకోండి',
    'initErrorTitle': 'లీఫ్‌గార్డ్ ప్రారంభం కాలేదు',
    'initErrorBody': 'మోడల్ ఫైళ్లు సరిగ్గా సెటప్ చేయబడ్డాయో లేదో నిర్ధారించుకోండి. సెటప్ దశల కోసం యాప్ README చూడండి.',
    'scanLeaf': 'ఆకును స్కాన్ చేయండి',
    'diagnoseNow': 'ఇప్పుడే నిర్ధారించండి',

    'settingsTitle': 'సెట్టింగ్‌లు',
    'settingsGeneral': 'సాధారణ',
    'settingsAccount': 'ఖాతా',
    'changeLanguage': 'భాష',
    'yourLocation': 'మీ ప్రాంతం',
    'locationNotSet': 'సెట్ చేయలేదు',
    'signedIn': 'సైన్ ఇన్ అయ్యారు',
    'notSignedInHint': 'అన్ని పరికరాల్లో మీ స్కాన్ చరిత్రను సింక్ చేయడానికి సైన్ ఇన్ చేయండి.',
    'signOut': 'సైన్ అవుట్ చేయండి',
    'appVersionLabel': 'లీఫ్‌గార్డ్ v1.0',

    'setupWelcomeTitle': 'లీఫ్‌గార్డ్‌కు స్వాగతం',
    'setupLanguagePrompt': 'మీరు ఉపయోగించాలనుకుంటున్న భాషను ఎంచుకోండి.',
    'setupLocationTitle': 'మీరు ఎక్కడ వ్యవసాయం చేస్తున్నారు?',
    'setupLocationPrompt': 'ఇది మీ ప్రాంతానికి తగిన సలహా ఇవ్వడంలో సహాయపడుతుంది. మీరు దీన్ని దాటవేసి తర్వాత జోడించవచ్చు.',
    'setupLocationHint': 'గ్రామం లేదా నగరం, రాష్ట్రం',
    'continueLabel': 'కొనసాగించండి',
    'skipForNow': 'ఇప్పుడు దాటవేయండి',

    'aiAssistantTitle': 'AI సహాయకుడు',
    'aiNotConfigured': 'AI సహాయకుడు పనిచేయడానికి బ్యాకెండ్ కనెక్షన్ అవసరం. Supabase మరియు ai-chat ఫంక్షన్‌ను సెటప్ చేయమని యాప్ డెవలపర్‌ను అడగండి.',
    'askAiCardTitle': 'AI సహాయకుడిని అడగండి',
    'askAiCardSubtitle': 'మీ భాషలో ఏదైనా పంట సమస్య గురించి సమాధానాలు పొందండి',
    'askAiAboutThis': 'దీని గురించి AIని అడగండి',
    'chatWelcomeMessage': 'నమస్కారం! నేను లీఫ్‌గార్డ్ యొక్క AI సహాయకుడిని. పంట వ్యాధులు, చికిత్సలు లేదా మీ మొక్కలపై మీరు చూస్తున్న దాని గురించి నన్ను ఏదైనా అడగండి.',
    'chatSeedIssueIntro': 'మీ స్కాన్‌లో సమస్య కనుగొనబడిందని నేను చూడగలుగుతున్నాను',
    'chatSeedHealthyIntro': 'శుభవార్త — మీ స్కాన్ ఆరోగ్యంగా కనిపించింది',
    'chatSeedPrompt': 'దీని గురించి నన్ను ఏదైనా అడగండి — కారణాలు, చికిత్స ఎంపికలు, లేదా అది వ్యాప్తి చెందకుండా ఎలా ఆపాలో.',
    'chatInputHint': 'మీ ప్రశ్నను టైప్ చేయండి…',
    'chatErrorGeneric': 'సహాయకుడిని చేరుకోలేకపోయాం. మీ కనెక్షన్‌ను తనిఖీ చేసి మళ్ళీ ప్రయత్నించండి.',
    'chatQuickCause': 'దీనికి కారణం ఏమిటి?',
    'chatQuickOrganicFirst': 'సురక్షితమైన సేంద్రియ పరిష్కారం ఏమిటి?',
    'chatQuickSpreadRisk': 'ఇది ఇతర మొక్కలకు వ్యాపిస్తుందా?',
    'chatQuickKeepHealthy': 'దీన్ని ఇలాగే ఆరోగ్యంగా ఎలా ఉంచాలి?',
    'chatQuickPreventFuture': 'భవిష్యత్ సమస్యలను ఎలా నివారించాలి?',
  };

  static const Map<String, String> _ta = {
    'appTagline': 'உங்கள் கேமராவை இலையின் மேல் வையுங்கள். சில விநாடிகளில் நோய் கண்டறியுங்கள் — சிக்னல் தேவையில்லை.',
    'loadingModel': 'மாடல் ஏற்றப்படுகிறது…',
    'navHome': 'முகப்பு',
    'navHistory': 'வரலாறு',
    'diseaseGuideTitle': 'நோய் வழிகாட்டி',
    'diseaseGuideSubtitle': 'லீஃப்கார்ட் அடையாளம் காணக்கூடிய நோய்களைப் பாருங்கள்',
    'recentScans': 'சமீபத்திய ஸ்கேன்கள்',
    'noScansYet': 'இதுவரை ஸ்கேன் இல்லை',
    'noScansHint': 'உங்கள் முதல் இலையை ஸ்கேன் செய்ய கீழே உள்ள கேமரா பொத்தானை அழுத்தவும்.',
    'cropTomato': 'தக்காளி',
    'cropPotato': 'உருளைக்கிழங்கு',
    'cropCorn': 'சோளம்',
    'scanInstruction': 'இலையை நடுவில் வையுங்கள், ஃபிரேமை நிரப்புங்கள், நிழலைத் தவிர்க்கவும்',
    'cameraPermissionError': 'கேமராவை அணுக முடியவில்லை. அமைப்புகளில் கேமரா அனுமதியை சரிபார்க்கவும்.',
    'captureError': 'அந்த புகைப்படத்தை எடுக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'galleryError': 'அந்த புகைப்படத்தைத் திறக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'galleryLabel': 'கேலரி',
    'cameraLabel': 'கேமரா',
    'goBack': 'திரும்பிச் செல்லுங்கள்',
    'analyzing': 'உங்கள் இலை பகுப்பாய்வு செய்யப்படுகிறது…',
    'runningOnDevice': 'இது முழுவதுமாக உங்கள் சாதனத்திலேயே இயங்குகிறது',
    'confidence': 'நம்பகத்தன்மை',
    'keepItThatWay': 'இப்படியே தொடருங்கள்',
    'scanAnother': 'மற்றொரு இலையை ஸ்கேன் செய்யுங்கள்',
    'tabOrganic': 'இயற்கை',
    'tabChemical': 'இரசாயன',
    'tabPrevention': 'தடுப்பு',
    'errorGeneric': 'ஏதோ தவறு நடந்தது.',
    'tryAgain': 'மீண்டும் முயற்சிக்கவும்',
    'severityHealthy': 'ஆரோக்கியமானது',
    'severityMild': 'லேசானது',
    'severitySevere': 'கவனம் தேவை',
    'historyTitle': 'வரலாறு',
    'historySubtitle': 'நீங்கள் ஸ்கேன் செய்த ஒவ்வொரு இலையும், இந்த சாதனத்தில் சேமிக்கப்பட்டுள்ளது.',
    'nothingScannedYet': 'இதுவரை எதுவும் ஸ்கேன் செய்யப்படவில்லை',
    'historyEmptyHint': 'உங்கள் ஸ்கேன் வரலாறு இங்கே தோன்றும்.',
    'welcomeBack': 'மீண்டும் வருக',
    'signInSubtitle': 'எல்லா சாதனங்களிலும் உங்கள் ஸ்கேன் வரலாற்றை ஒத்திசைக்க உள்நுழையவும்.',
    'emailHint': 'மின்னஞ்சல்',
    'passwordHint': 'கடவுச்சொல்',
    'signIn': 'உள்நுழையவும்',
    'noAccountSignUp': 'கணக்கு இல்லையா? பதிவு செய்யவும்',
    'continueWithoutAccount': 'கணக்கு இல்லாமல் தொடரவும்',
    'createAccount': 'கணக்கை உருவாக்கவும்',
    'signupIntro':
        'உங்கள் ஸ்கேன்கள் எப்படியும் இந்த சாதனத்திலேயே இருக்கும் — ஒரு கணக்கு அவற்றை ஒத்திசைக்கவும் மீட்டெடுக்கவும் மட்டுமே உதவும்.',
    'organicTreatment': 'இயற்கை சிகிச்சை',
    'chemicalTreatment': 'இரசாயன சிகிச்சை',
    'preventionTips': 'தடுப்பு குறிப்புகள்',
    'chooseLanguage': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    'initErrorTitle': 'லீஃப்கார்டைத் தொடங்க முடியவில்லை',
    'initErrorBody': 'மாடல் கோப்புகள் சரியாக அமைக்கப்பட்டுள்ளதா என்பதை உறுதிப்படுத்தவும். அமைவு படிகளுக்கு ஆப் README ஐப் பார்க்கவும்.',
    'scanLeaf': 'இலையை ஸ்கேன் செய்யுங்கள்',
    'diagnoseNow': 'இப்போதே கண்டறியவும்',

    'settingsTitle': 'அமைப்புகள்',
    'settingsGeneral': 'பொது',
    'settingsAccount': 'கணக்கு',
    'changeLanguage': 'மொழி',
    'yourLocation': 'உங்கள் இருப்பிடம்',
    'locationNotSet': 'அமைக்கப்படவில்லை',
    'signedIn': 'உள்நுழைந்துள்ளீர்கள்',
    'notSignedInHint': 'அனைத்து சாதனங்களிலும் உங்கள் ஸ்கேன் வரலாற்றை ஒத்திசைக்க உள்நுழையவும்.',
    'signOut': 'வெளியேறு',
    'appVersionLabel': 'லீஃப்கார்ட் v1.0',

    'setupWelcomeTitle': 'லீஃப்கார்டுக்கு வரவேற்கிறோம்',
    'setupLanguagePrompt': 'நீங்கள் பயன்படுத்த விரும்பும் மொழியைத் தேர்ந்தெடுக்கவும்.',
    'setupLocationTitle': 'நீங்கள் எங்கு விவசாயம் செய்கிறீர்கள்?',
    'setupLocationPrompt': 'இது உங்கள் பகுதிக்கு ஏற்ற ஆலோசனையை வழங்க உதவும். இதைத் தவிர்த்து பின்னர் சேர்க்கலாம்.',
    'setupLocationHint': 'கிராமம் அல்லது நகரம், மாநிலம்',
    'continueLabel': 'தொடரவும்',
    'skipForNow': 'இப்போதைக்கு தவிர்க்கவும்',

    'aiAssistantTitle': 'AI உதவியாளர்',
    'aiNotConfigured': 'AI உதவியாளர் வேலை செய்ய பேக்எண்ட் இணைப்பு தேவை. Supabase மற்றும் ai-chat செயல்பாட்டை அமைக்குமாறு ஆப் டெவலப்பரிடம் கேளுங்கள்.',
    'askAiCardTitle': 'AI உதவியாளரிடம் கேளுங்கள்',
    'askAiCardSubtitle': 'உங்கள் மொழியில் எந்த பயிர் பிரச்சனைக்கும் பதில் பெறுங்கள்',
    'askAiAboutThis': 'இதைப் பற்றி AI-யிடம் கேளுங்கள்',
    'chatWelcomeMessage': 'வணக்கம்! நான் லீஃப்கார்டின் AI உதவியாளர். பயிர் நோய்கள், சிகிச்சைகள் அல்லது உங்கள் தாவரங்களில் நீங்கள் காண்பது பற்றி என்னிடம் எதுவும் கேளுங்கள்.',
    'chatSeedIssueIntro': 'உங்கள் ஸ்கேனில் ஒரு பிரச்சனை கண்டறியப்பட்டதை நான் காண்கிறேன்',
    'chatSeedHealthyIntro': 'நல்ல செய்தி — உங்கள் ஸ்கேன் ஆரோக்கியமாக இருந்தது',
    'chatSeedPrompt': 'இதைப் பற்றி என்னிடம் எதுவும் கேளுங்கள் — காரணங்கள், சிகிச்சை விருப்பங்கள், அல்லது அது பரவாமல் தடுப்பது எப்படி.',
    'chatInputHint': 'உங்கள் கேள்வியை தட்டச்சு செய்யவும்…',
    'chatErrorGeneric': 'உதவியாளரை அணுக முடியவில்லை. உங்கள் இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    'chatQuickCause': 'இதற்கு காரணம் என்ன?',
    'chatQuickOrganicFirst': 'பாதுகாப்பான கரிம தீர்வு என்ன?',
    'chatQuickSpreadRisk': 'இது மற்ற தாவரங்களுக்கு பரவுமா?',
    'chatQuickKeepHealthy': 'இதை இப்படியே ஆரோக்கியமாக எப்படி வைத்திருப்பது?',
    'chatQuickPreventFuture': 'எதிர்கால பிரச்சனைகளை எப்படி தடுப்பது?',
  };

  static const Map<String, String> _bn = {
    'appTagline': 'আপনার ক্যামেরা পাতার উপর ধরুন। কয়েক সেকেন্ডে রোগ নির্ণয় পান — সিগন্যালের দরকার নেই।',
    'loadingModel': 'মডেল লোড হচ্ছে…',
    'navHome': 'হোম',
    'navHistory': 'ইতিহাস',
    'diseaseGuideTitle': 'রোগ গাইড',
    'diseaseGuideSubtitle': 'লিফগার্ড যেসব রোগ শনাক্ত করতে পারে তা দেখুন',
    'recentScans': 'সাম্প্রতিক স্ক্যান',
    'noScansYet': 'এখনো কোনো স্ক্যান নেই',
    'noScansHint': 'প্রথম পাতা স্ক্যান করতে নিচের ক্যামেরা বোতাম চাপুন।',
    'cropTomato': 'টমেটো',
    'cropPotato': 'আলু',
    'cropCorn': 'ভুট্টা',
    'scanInstruction': 'পাতাটি মাঝখানে রাখুন, ফ্রেম পূর্ণ করুন, ছায়া এড়িয়ে চলুন',
    'cameraPermissionError': 'ক্যামেরা অ্যাক্সেস করা যায়নি। সেটিংসে ক্যামেরার অনুমতি পরীক্ষা করুন।',
    'captureError': 'সেই ছবি তোলা যায়নি। আবার চেষ্টা করুন।',
    'galleryError': 'সেই ছবি খোলা যায়নি। আবার চেষ্টা করুন।',
    'galleryLabel': 'গ্যালারি',
    'cameraLabel': 'ক্যামেরা',
    'goBack': 'ফিরে যান',
    'analyzing': 'আপনার পাতা বিশ্লেষণ করা হচ্ছে…',
    'runningOnDevice': 'এটি সম্পূর্ণভাবে আপনার ডিভাইসেই চলছে',
    'confidence': 'নির্ভরযোগ্যতা',
    'keepItThatWay': 'এভাবেই রাখুন',
    'scanAnother': 'আরেকটি পাতা স্ক্যান করুন',
    'tabOrganic': 'জৈব',
    'tabChemical': 'রাসায়নিক',
    'tabPrevention': 'প্রতিরোধ',
    'errorGeneric': 'কিছু ভুল হয়েছে।',
    'tryAgain': 'আবার চেষ্টা করুন',
    'severityHealthy': 'সুস্থ',
    'severityMild': 'মৃদু',
    'severitySevere': 'মনোযোগ প্রয়োজন',
    'historyTitle': 'ইতিহাস',
    'historySubtitle': 'আপনার স্ক্যান করা প্রতিটি পাতা এই ডিভাইসে সংরক্ষিত।',
    'nothingScannedYet': 'এখনো কিছু স্ক্যান করা হয়নি',
    'historyEmptyHint': 'আপনার স্ক্যান ইতিহাস এখানে দেখা যাবে।',
    'welcomeBack': 'আবার স্বাগতম',
    'signInSubtitle': 'সব ডিভাইসে আপনার স্ক্যান ইতিহাস সিঙ্ক করতে সাইন ইন করুন।',
    'emailHint': 'ইমেইল',
    'passwordHint': 'পাসওয়ার্ড',
    'signIn': 'সাইন ইন করুন',
    'noAccountSignUp': 'অ্যাকাউন্ট নেই? সাইন আপ করুন',
    'continueWithoutAccount': 'অ্যাকাউন্ট ছাড়াই চালিয়ে যান',
    'createAccount': 'অ্যাকাউন্ট তৈরি করুন',
    'signupIntro':
        'আপনার স্ক্যান যেভাবেই হোক এই ডিভাইসে থেকে যায় — অ্যাকাউন্ট শুধু সেগুলো সিঙ্ক ও পুনরুদ্ধার করতে সাহায্য করে।',
    'organicTreatment': 'জৈব চিকিৎসা',
    'chemicalTreatment': 'রাসায়নিক চিকিৎসা',
    'preventionTips': 'প্রতিরোধের উপায়',
    'chooseLanguage': 'আপনার ভাষা বেছে নিন',
    'initErrorTitle': 'লিফগার্ড চালু করা যায়নি',
    'initErrorBody': 'মডেল ফাইলগুলো সঠিকভাবে সেট করা আছে কিনা নিশ্চিত করুন। সেটআপ ধাপের জন্য অ্যাপের README দেখুন।',
    'scanLeaf': 'একটি পাতা স্ক্যান করুন',
    'diagnoseNow': 'এখনই নির্ণয় করুন',

    'settingsTitle': 'সেটিংস',
    'settingsGeneral': 'সাধারণ',
    'settingsAccount': 'অ্যাকাউন্ট',
    'changeLanguage': 'ভাষা',
    'yourLocation': 'আপনার অবস্থান',
    'locationNotSet': 'সেট করা হয়নি',
    'signedIn': 'সাইন ইন করা আছে',
    'notSignedInHint': 'সমস্ত ডিভাইসে আপনার স্ক্যান ইতিহাস সিঙ্ক করতে সাইন ইন করুন।',
    'signOut': 'সাইন আউট করুন',
    'appVersionLabel': 'লীফগার্ড v1.0',

    'setupWelcomeTitle': 'লীফগার্ডে স্বাগতম',
    'setupLanguagePrompt': 'আপনি যে ভাষা ব্যবহার করতে চান তা নির্বাচন করুন।',
    'setupLocationTitle': 'আপনি কোথায় চাষ করেন?',
    'setupLocationPrompt': 'এটি আপনার অঞ্চল অনুযায়ী পরামর্শ দিতে সাহায্য করে। আপনি এটি এড়িয়ে পরে যোগ করতে পারেন।',
    'setupLocationHint': 'গ্রাম বা শহর, রাজ্য',
    'continueLabel': 'চালিয়ে যান',
    'skipForNow': 'এখনকার মতো এড়িয়ে যান',

    'aiAssistantTitle': 'এআই সহকারী',
    'aiNotConfigured': 'এআই সহকারীর কাজ করার জন্য ব্যাকএন্ড সংযোগ প্রয়োজন। অ্যাপ ডেভেলপারকে Supabase এবং ai-chat ফাংশন সেট আপ করতে বলুন।',
    'askAiCardTitle': 'এআই সহকারীকে জিজ্ঞাসা করুন',
    'askAiCardSubtitle': 'আপনার ভাষায় যেকোনো ফসলের সমস্যা সম্পর্কে উত্তর পান',
    'askAiAboutThis': 'এই বিষয়ে এআইকে জিজ্ঞাসা করুন',
    'chatWelcomeMessage': 'নমস্কার! আমি লীফগার্ডের এআই সহকারী। ফসলের রোগ, চিকিৎসা বা আপনার গাছে যা দেখছেন তা নিয়ে আমাকে যেকোনো কিছু জিজ্ঞাসা করুন।',
    'chatSeedIssueIntro': 'আমি দেখতে পাচ্ছি আপনার স্ক্যানে একটি সমস্যা পাওয়া গেছে',
    'chatSeedHealthyIntro': 'সুখবর — আপনার স্ক্যান সুস্থ পাওয়া গেছে',
    'chatSeedPrompt': 'এই বিষয়ে আমাকে যেকোনো কিছু জিজ্ঞাসা করুন — কারণ, চিকিৎসার বিকল্প, বা এটি ছড়িয়ে পড়া বন্ধ করার উপায়।',
    'chatInputHint': 'আপনার প্রশ্ন লিখুন…',
    'chatErrorGeneric': 'সহকারীর কাছে পৌঁছানো যায়নি। আপনার সংযোগ পরীক্ষা করুন এবং আবার চেষ্টা করুন।',
    'chatQuickCause': 'এর কারণ কী?',
    'chatQuickOrganicFirst': 'সবচেয়ে নিরাপদ জৈব সমাধান কী?',
    'chatQuickSpreadRisk': 'এটি কি অন্য গাছে ছড়াবে?',
    'chatQuickKeepHealthy': 'আমি কীভাবে এটি এভাবে সুস্থ রাখব?',
    'chatQuickPreventFuture': 'ভবিষ্যতের সমস্যা কীভাবে প্রতিরোধ করব?',
  };

  static const Map<String, String> _gu = {
    'appTagline': 'તમારો કેમેરો પાન પર રાખો. થોડીક સેકંડમાં નિદાન મેળવો — સિગ્નલની જરૂર નથી.',
    'loadingModel': 'મોડેલ લોડ થઈ રહ્યું છે…',
    'navHome': 'હોમ',
    'navHistory': 'ઇતિહાસ',
    'diseaseGuideTitle': 'રોગ માર્ગદર્શિકા',
    'diseaseGuideSubtitle': 'લીફગાર્ડ ઓળખી શકે તેવા રોગો જુઓ',
    'recentScans': 'તાજેતરના સ્કેન',
    'noScansYet': 'હજી કોઈ સ્કેન નથી',
    'noScansHint': 'તમારું પહેલું પાન સ્કેન કરવા માટે નીચે કેમેરા બટન દબાવો.',
    'cropTomato': 'ટામેટા',
    'cropPotato': 'બટાકા',
    'cropCorn': 'મકાઈ',
    'scanInstruction': 'પાનને મધ્યમાં રાખો, ફ્રેમ ભરો, છાયા ટાળો',
    'cameraPermissionError': 'કેમેરાનો ઉપયોગ કરી શકાયો નથી. સેટિંગ્સમાં કેમેરાની પરવાનગી તપાસો.',
    'captureError': 'તે ફોટો લઈ શકાયો નથી. ફરી પ્રયાસ કરો.',
    'galleryError': 'તે ફોટો ખોલી શકાયો નથી. ફરી પ્રયાસ કરો.',
    'galleryLabel': 'ગેલેરી',
    'cameraLabel': 'કેમેરો',
    'goBack': 'પાછા જાઓ',
    'analyzing': 'તમારા પાનનું વિશ્લેષણ થઈ રહ્યું છે…',
    'runningOnDevice': 'આ સંપૂર્ણપણે તમારા ડિવાઇસ પર જ ચાલે છે',
    'confidence': 'વિશ્વસનીયતા',
    'keepItThatWay': 'આમ જ ચાલુ રાખો',
    'scanAnother': 'બીજું પાન સ્કેન કરો',
    'tabOrganic': 'જૈવિક',
    'tabChemical': 'રાસાયણિક',
    'tabPrevention': 'નિવારણ',
    'errorGeneric': 'કંઈક ખોટું થયું.',
    'tryAgain': 'ફરી પ્રયાસ કરો',
    'severityHealthy': 'તંદુરસ્ત',
    'severityMild': 'હળવું',
    'severitySevere': 'ધ્યાન આપવાની જરૂર',
    'historyTitle': 'ઇતિહાસ',
    'historySubtitle': 'તમે સ્કેન કરેલા બધા પાન, આ ડિવાઇસ પર સંગ્રહાયેલા.',
    'nothingScannedYet': 'હજી કંઈ સ્કેન થયું નથી',
    'historyEmptyHint': 'તમારો સ્કેન ઇતિહાસ અહીં દેખાશે.',
    'welcomeBack': 'પાછા આવવા બદલ સ્વાગત છે',
    'signInSubtitle': 'બધા ડિવાઇસ પર તમારો સ્કેન ઇતિહાસ સિંક કરવા સાઇન ઇન કરો.',
    'emailHint': 'ઇમેઇલ',
    'passwordHint': 'પાસવર્ડ',
    'signIn': 'સાઇન ઇન કરો',
    'noAccountSignUp': 'ખાતું નથી? સાઇન અપ કરો',
    'continueWithoutAccount': 'ખાતા વગર ચાલુ રાખો',
    'createAccount': 'ખાતું બનાવો',
    'signupIntro':
        'તમારા સ્કેન ગમે તે રીતે આ ડિવાઇસ પર જ રહે છે — ખાતું ફક્ત તેમને સિંક અને પુનઃપ્રાપ્ત કરવામાં મદદ કરે છે.',
    'organicTreatment': 'જૈવિક સારવાર',
    'chemicalTreatment': 'રાસાયણિક સારવાર',
    'preventionTips': 'નિવારણના ઉપાયો',
    'chooseLanguage': 'તમારી ભાષા પસંદ કરો',
    'initErrorTitle': 'લીફગાર્ડ શરૂ થઈ શક્યું નથી',
    'initErrorBody': 'ખાતરી કરો કે મોડેલ ફાઈલો યોગ્ય રીતે સેટ છે. સેટઅપ પગલાં માટે એપની README જુઓ.',
    'scanLeaf': 'પાન સ્કેન કરો',
    'diagnoseNow': 'હમણાં નિદાન કરો',

    'settingsTitle': 'સેટિંગ્સ',
    'settingsGeneral': 'સામાન્ય',
    'settingsAccount': 'ખાતું',
    'changeLanguage': 'ભાષા',
    'yourLocation': 'તમારું સ્થાન',
    'locationNotSet': 'સેટ નથી',
    'signedIn': 'સાઇન ઇન છે',
    'notSignedInHint': 'તમામ ડિવાઇસ પર તમારો સ્કેન ઇતિહાસ સિંક કરવા સાઇન ઇન કરો.',
    'signOut': 'સાઇન આઉટ કરો',
    'appVersionLabel': 'લીફગાર્ડ v1.0',

    'setupWelcomeTitle': 'લીફગાર્ડમાં આપનું સ્વાગત છે',
    'setupLanguagePrompt': 'તમે ઉપયોગ કરવા માંગો છો તે ભાષા પસંદ કરો.',
    'setupLocationTitle': 'તમે ક્યાં ખેતી કરો છો?',
    'setupLocationPrompt': 'આ તમારા વિસ્તાર પ્રમાણે સલાહ આપવામાં મદદ કરે છે. તમે આ છોડીને પછી ઉમેરી શકો છો.',
    'setupLocationHint': 'ગામ અથવા શહેર, રાજ્ય',
    'continueLabel': 'ચાલુ રાખો',
    'skipForNow': 'હમણાં માટે છોડો',

    'aiAssistantTitle': 'AI સહાયક',
    'aiNotConfigured': 'AI સહાયકને કામ કરવા માટે બેકએન્ડ કનેક્શનની જરૂર છે. એપ ડેવલપરને Supabase અને ai-chat ફંક્શન સેટ કરવા કહો.',
    'askAiCardTitle': 'AI સહાયકને પૂછો',
    'askAiCardSubtitle': 'તમારી ભાષામાં કોઈપણ પાક સમસ્યા વિશે જવાબ મેળવો',
    'askAiAboutThis': 'આ વિશે AI ને પૂછો',
    'chatWelcomeMessage': 'નમસ્તે! હું લીફગાર્ડનો AI સહાયક છું. પાક રોગો, સારવાર અથવા તમારા છોડ પર તમે શું જુઓ છો તે વિશે મને કંઈપણ પૂછો.',
    'chatSeedIssueIntro': 'હું જોઈ શકું છું કે તમારા સ્કેનમાં સમસ્યા મળી છે',
    'chatSeedHealthyIntro': 'સારા સમાચાર — તમારો સ્કેન સ્વસ્થ મળ્યો',
    'chatSeedPrompt': 'આ વિશે મને કંઈપણ પૂછો — કારણો, સારવારના વિકલ્પો, અથવા તેને ફેલાતું કેવી રીતે રોકવું.',
    'chatInputHint': 'તમારો પ્રશ્ન લખો…',
    'chatErrorGeneric': 'સહાયક સુધી પહોંચી શકાયું નથી. તમારું કનેક્શન તપાસો અને ફરી પ્રયાસ કરો.',
    'chatQuickCause': 'આનું કારણ શું છે?',
    'chatQuickOrganicFirst': 'સૌથી સુરક્ષિત જૈવિક ઉપાય શું છે?',
    'chatQuickSpreadRisk': 'શું આ અન્ય છોડમાં ફેલાશે?',
    'chatQuickKeepHealthy': 'હું આને આ રીતે સ્વસ્થ કેવી રીતે રાખું?',
    'chatQuickPreventFuture': 'ભવિષ્યની સમસ્યાઓ કેવી રીતે અટકાવવી?',
  };

  static const Map<String, String> _kn = {
    'appTagline': 'ನಿಮ್ಮ ಕ್ಯಾಮೆರಾವನ್ನು ಎಲೆಯ ಮೇಲೆ ಇಡಿ. ಕೆಲವೇ ಸೆಕೆಂಡುಗಳಲ್ಲಿ ರೋಗ ನಿರ್ಣಯ ಪಡೆಯಿರಿ — ಸಿಗ್ನಲ್ ಅಗತ್ಯವಿಲ್ಲ.',
    'loadingModel': 'ಮಾದರಿ ಲೋಡ್ ಆಗುತ್ತಿದೆ…',
    'navHome': 'ಮುಖಪುಟ',
    'navHistory': 'ಇತಿಹಾಸ',
    'diseaseGuideTitle': 'ರೋಗ ಮಾರ್ಗದರ್ಶಿ',
    'diseaseGuideSubtitle': 'ಲೀಫ್‌ಗಾರ್ಡ್ ಗುರುತಿಸಬಲ್ಲ ರೋಗಗಳನ್ನು ನೋಡಿ',
    'recentScans': 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
    'noScansYet': 'ಇನ್ನೂ ಸ್ಕ್ಯಾನ್‌ಗಳಿಲ್ಲ',
    'noScansHint': 'ನಿಮ್ಮ ಮೊದಲ ಎಲೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಲು ಕೆಳಗಿನ ಕ್ಯಾಮೆರಾ ಬಟನ್ ಒತ್ತಿ.',
    'cropTomato': 'ಟೊಮೇಟೊ',
    'cropPotato': 'ಆಲೂಗಡ್ಡೆ',
    'cropCorn': 'ಜೋಳ',
    'scanInstruction': 'ಎಲೆಯನ್ನು ಮಧ್ಯದಲ್ಲಿ ಇಡಿ, ಫ್ರೇಮ್ ತುಂಬಿಸಿ, ನೆರಳು ತಪ್ಪಿಸಿ',
    'cameraPermissionError': 'ಕ್ಯಾಮೆರಾ ಪ್ರವೇಶಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಸೆಟ್ಟಿಂಗ್‌ಗಳಲ್ಲಿ ಕ್ಯಾಮೆರಾ ಅನುಮತಿ ಪರಿಶೀಲಿಸಿ.',
    'captureError': 'ಆ ಫೋಟೋ ತೆಗೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'galleryError': 'ಆ ಫೋಟೋ ತೆರೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'galleryLabel': 'ಗ್ಯಾಲರಿ',
    'cameraLabel': 'ಕ್ಯಾಮೆರಾ',
    'goBack': 'ಹಿಂದೆ ಹೋಗಿ',
    'analyzing': 'ನಿಮ್ಮ ಎಲೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ…',
    'runningOnDevice': 'ಇದು ಸಂಪೂರ್ಣವಾಗಿ ನಿಮ್ಮ ಸಾಧನದಲ್ಲೇ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ',
    'confidence': 'ವಿಶ್ವಾಸಾರ್ಹತೆ',
    'keepItThatWay': 'ಹೀಗೆಯೇ ಮುಂದುವರಿಸಿ',
    'scanAnother': 'ಇನ್ನೊಂದು ಎಲೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'tabOrganic': 'ಸಾವಯವ',
    'tabChemical': 'ರಾಸಾಯನಿಕ',
    'tabPrevention': 'ತಡೆಗಟ್ಟುವಿಕೆ',
    'errorGeneric': 'ಏನೋ ತಪ್ಪಾಗಿದೆ.',
    'tryAgain': 'ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ',
    'severityHealthy': 'ಆರೋಗ್ಯಕರ',
    'severityMild': 'ಸೌಮ್ಯ',
    'severitySevere': 'ಗಮನ ಅಗತ್ಯ',
    'historyTitle': 'ಇತಿಹಾಸ',
    'historySubtitle': 'ನೀವು ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ಪ್ರತಿ ಎಲೆ, ಈ ಸಾಧನದಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗಿದೆ.',
    'nothingScannedYet': 'ಇನ್ನೂ ಏನನ್ನೂ ಸ್ಕ್ಯಾನ್ ಮಾಡಿಲ್ಲ',
    'historyEmptyHint': 'ನಿಮ್ಮ ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸ ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತದೆ.',
    'welcomeBack': 'ಮತ್ತೆ ಸ್ವಾಗತ',
    'signInSubtitle': 'ಎಲ್ಲಾ ಸಾಧನಗಳಲ್ಲಿ ನಿಮ್ಮ ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸವನ್ನು ಸಿಂಕ್ ಮಾಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    'emailHint': 'ಇಮೇಲ್',
    'passwordHint': 'ಪಾಸ್‌ವರ್ಡ್',
    'signIn': 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'noAccountSignUp': 'ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'continueWithoutAccount': 'ಖಾತೆ ಇಲ್ಲದೆ ಮುಂದುವರಿಸಿ',
    'createAccount': 'ಖಾತೆ ರಚಿಸಿ',
    'signupIntro':
        'ನಿಮ್ಮ ಸ್ಕ್ಯಾನ್‌ಗಳು ಹೇಗಿದ್ದರೂ ಈ ಸಾಧನದಲ್ಲೇ ಉಳಿಯುತ್ತವೆ — ಖಾತೆ ಅವುಗಳನ್ನು ಸಿಂಕ್ ಮತ್ತು ಮರುಪಡೆಯಲು ಮಾತ್ರ ಸಹಾಯ ಮಾಡುತ್ತದೆ.',
    'organicTreatment': 'ಸಾವಯವ ಚಿಕಿತ್ಸೆ',
    'chemicalTreatment': 'ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ',
    'preventionTips': 'ತಡೆಗಟ್ಟುವ ಸಲಹೆಗಳು',
    'chooseLanguage': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'initErrorTitle': 'ಲೀಫ್‌ಗಾರ್ಡ್ ಪ್ರಾರಂಭಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ',
    'initErrorBody': 'ಮಾದರಿ ಫೈಲ್‌ಗಳು ಸರಿಯಾಗಿ ಹೊಂದಿಸಲಾಗಿದೆಯೇ ಎಂದು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ. ಸೆಟಪ್ ಹಂತಗಳಿಗಾಗಿ ಆ್ಯಪ್‌ನ README ನೋಡಿ.',
    'scanLeaf': 'ಎಲೆಯನ್ನು ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'diagnoseNow': 'ಈಗ ನಿರ್ಣಯಿಸಿ',

    'settingsTitle': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'settingsGeneral': 'ಸಾಮಾನ್ಯ',
    'settingsAccount': 'ಖಾತೆ',
    'changeLanguage': 'ಭಾಷೆ',
    'yourLocation': 'ನಿಮ್ಮ ಸ್ಥಳ',
    'locationNotSet': 'ಹೊಂದಿಸಿಲ್ಲ',
    'signedIn': 'ಸೈನ್ ಇನ್ ಆಗಿದೆ',
    'notSignedInHint': 'ಎಲ್ಲಾ ಸಾಧನಗಳಲ್ಲಿ ನಿಮ್ಮ ಸ್ಕ್ಯಾನ್ ಇತಿಹಾಸವನ್ನು ಸಿಂಕ್ ಮಾಡಲು ಸೈನ್ ಇನ್ ಮಾಡಿ.',
    'signOut': 'ಸೈನ್ ಔಟ್ ಮಾಡಿ',
    'appVersionLabel': 'ಲೀಫ್‌ಗಾರ್ಡ್ v1.0',

    'setupWelcomeTitle': 'ಲೀಫ್‌ಗಾರ್ಡ್‌ಗೆ ಸುಸ್ವಾಗತ',
    'setupLanguagePrompt': 'ನೀವು ಬಳಸಲು ಬಯಸುವ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'setupLocationTitle': 'ನೀವು ಎಲ್ಲಿ ಕೃಷಿ ಮಾಡುತ್ತೀರಿ?',
    'setupLocationPrompt': 'ಇದು ನಿಮ್ಮ ಪ್ರದೇಶಕ್ಕೆ ತಕ್ಕಂತೆ ಸಲಹೆ ನೀಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ. ನೀವು ಇದನ್ನು ಬಿಟ್ಟು ನಂತರ ಸೇರಿಸಬಹುದು.',
    'setupLocationHint': 'ಗ್ರಾಮ ಅಥವಾ ನಗರ, ರಾಜ್ಯ',
    'continueLabel': 'ಮುಂದುವರಿಸಿ',
    'skipForNow': 'ಈಗ ಬಿಟ್ಟುಬಿಡಿ',

    'aiAssistantTitle': 'AI ಸಹಾಯಕ',
    'aiNotConfigured': 'AI ಸಹಾಯಕ ಕೆಲಸ ಮಾಡಲು ಬ್ಯಾಕೆಂಡ್ ಸಂಪರ್ಕದ ಅಗತ್ಯವಿದೆ. Supabase ಮತ್ತು ai-chat ಫಂಕ್ಷನ್ ಅನ್ನು ಹೊಂದಿಸಲು ಅಪ್ಲಿಕೇಶನ್ ಡೆವಲಪರ್‌ಗೆ ಕೇಳಿ.',
    'askAiCardTitle': 'AI ಸಹಾಯಕರನ್ನು ಕೇಳಿ',
    'askAiCardSubtitle': 'ನಿಮ್ಮ ಭಾಷೆಯಲ್ಲಿ ಯಾವುದೇ ಬೆಳೆ ಸಮಸ್ಯೆಯ ಬಗ್ಗೆ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ',
    'askAiAboutThis': 'ಇದರ ಬಗ್ಗೆ AI ಅನ್ನು ಕೇಳಿ',
    'chatWelcomeMessage': 'ನಮಸ್ಕಾರ! ನಾನು ಲೀಫ್‌ಗಾರ್ಡ್‌ನ AI ಸಹಾಯಕ. ಬೆಳೆ ರೋಗಗಳು, ಚಿಕಿತ್ಸೆಗಳು ಅಥವಾ ನಿಮ್ಮ ಸಸ್ಯಗಳಲ್ಲಿ ನೀವು ಏನು ನೋಡುತ್ತಿದ್ದೀರಿ ಎಂಬುದರ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನಾದರೂ ಕೇಳಿ.',
    'chatSeedIssueIntro': 'ನಿಮ್ಮ ಸ್ಕ್ಯಾನ್‌ನಲ್ಲಿ ಸಮಸ್ಯೆ ಕಂಡುಬಂದಿದೆ ಎಂದು ನಾನು ನೋಡಬಲ್ಲೆ',
    'chatSeedHealthyIntro': 'ಒಳ್ಳೆಯ ಸುದ್ದಿ — ನಿಮ್ಮ ಸ್ಕ್ಯಾನ್ ಆರೋಗ್ಯಕರವಾಗಿ ಕಂಡುಬಂದಿದೆ',
    'chatSeedPrompt': 'ಇದರ ಬಗ್ಗೆ ನನ್ನನ್ನು ಏನಾದರೂ ಕೇಳಿ — ಕಾರಣಗಳು, ಚಿಕಿತ್ಸಾ ಆಯ್ಕೆಗಳು, ಅಥವಾ ಅದು ಹರಡುವುದನ್ನು ತಡೆಯುವುದು ಹೇಗೆ.',
    'chatInputHint': 'ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಟೈಪ್ ಮಾಡಿ…',
    'chatErrorGeneric': 'ಸಹಾಯಕರನ್ನು ತಲುಪಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ನಿಮ್ಮ ಸಂಪರ್ಕವನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'chatQuickCause': 'ಇದಕ್ಕೆ ಕಾರಣವೇನು?',
    'chatQuickOrganicFirst': 'ಅತ್ಯಂತ ಸುರಕ್ಷಿತ ಸಾವಯವ ಪರಿಹಾರ ಯಾವುದು?',
    'chatQuickSpreadRisk': 'ಇದು ಇತರ ಸಸ್ಯಗಳಿಗೆ ಹರಡುತ್ತದೆಯೇ?',
    'chatQuickKeepHealthy': 'ಇದನ್ನು ಈ ರೀತಿ ಆರೋಗ್ಯಕರವಾಗಿ ಹೇಗೆ ಇಡುವುದು?',
    'chatQuickPreventFuture': 'ಭವಿಷ್ಯದ ಸಮಸ್ಯೆಗಳನ್ನು ಹೇಗೆ ತಡೆಯುವುದು?',
  };

  static const Map<String, String> _pa = {
    'appTagline': "ਆਪਣਾ ਕੈਮਰਾ ਪੱਤੇ 'ਤੇ ਰੱਖੋ। ਕੁਝ ਹੀ ਸਕਿੰਟਾਂ ਵਿੱਚ ਜਾਂਚ ਪਾਓ — ਸਿਗਨਲ ਦੀ ਲੋੜ ਨਹੀਂ।",
    'loadingModel': 'ਮਾਡਲ ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ…',
    'navHome': 'ਹੋਮ',
    'navHistory': 'ਇਤਿਹਾਸ',
    'diseaseGuideTitle': 'ਰੋਗ ਗਾਈਡ',
    'diseaseGuideSubtitle': 'ਲੀਫਗਾਰਡ ਜਿਨ੍ਹਾਂ ਰੋਗਾਂ ਨੂੰ ਪਛਾਣ ਸਕਦਾ ਹੈ ਉਹ ਵੇਖੋ',
    'recentScans': 'ਹਾਲੀਆ ਸਕੈਨ',
    'noScansYet': 'ਅਜੇ ਕੋਈ ਸਕੈਨ ਨਹੀਂ',
    'noScansHint': 'ਆਪਣਾ ਪਹਿਲਾ ਪੱਤਾ ਸਕੈਨ ਕਰਨ ਲਈ ਹੇਠਾਂ ਕੈਮਰਾ ਬਟਨ ਦਬਾਓ।',
    'cropTomato': 'ਟਮਾਟਰ',
    'cropPotato': 'ਆਲੂ',
    'cropCorn': 'ਮੱਕੀ',
    'scanInstruction': 'ਪੱਤੇ ਨੂੰ ਵਿਚਕਾਰ ਰੱਖੋ, ਫਰੇਮ ਭਰੋ, ਪਰਛਾਵੇਂ ਤੋਂ ਬਚੋ',
    'cameraPermissionError': 'ਕੈਮਰੇ ਤੱਕ ਪਹੁੰਚ ਨਹੀਂ ਹੋ ਸਕੀ। ਸੈਟਿੰਗਾਂ ਵਿੱਚ ਕੈਮਰਾ ਇਜਾਜ਼ਤ ਜਾਂਚੋ।',
    'captureError': 'ਉਹ ਫੋਟੋ ਨਹੀਂ ਲਈ ਜਾ ਸਕੀ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    'galleryError': 'ਉਹ ਫੋਟੋ ਨਹੀਂ ਖੁੱਲ੍ਹ ਸਕੀ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    'galleryLabel': 'ਗੈਲਰੀ',
    'cameraLabel': 'ਕੈਮਰਾ',
    'goBack': 'ਵਾਪਸ ਜਾਓ',
    'analyzing': 'ਤੁਹਾਡੇ ਪੱਤੇ ਦੀ ਜਾਂਚ ਹੋ ਰਹੀ ਹੈ…',
    'runningOnDevice': "ਇਹ ਪੂਰੀ ਤਰ੍ਹਾਂ ਤੁਹਾਡੀ ਡਿਵਾਈਸ 'ਤੇ ਹੀ ਚੱਲ ਰਿਹਾ ਹੈ",
    'confidence': 'ਭਰੋਸੇਯੋਗਤਾ',
    'keepItThatWay': 'ਇਵੇਂ ਹੀ ਰੱਖੋ',
    'scanAnother': 'ਇੱਕ ਹੋਰ ਪੱਤਾ ਸਕੈਨ ਕਰੋ',
    'tabOrganic': 'ਜੈਵਿਕ',
    'tabChemical': 'ਰਸਾਇਣਕ',
    'tabPrevention': 'ਰੋਕਥਾਮ',
    'errorGeneric': 'ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।',
    'tryAgain': 'ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    'severityHealthy': 'ਸਿਹਤਮੰਦ',
    'severityMild': 'ਹਲਕਾ',
    'severitySevere': 'ਧਿਆਨ ਦੀ ਲੋੜ',
    'historyTitle': 'ਇਤਿਹਾਸ',
    'historySubtitle': "ਤੁਹਾਡੇ ਸਕੈਨ ਕੀਤੇ ਸਾਰੇ ਪੱਤੇ, ਇਸ ਡਿਵਾਈਸ 'ਤੇ ਸੰਭਾਲੇ ਗਏ।",
    'nothingScannedYet': 'ਅਜੇ ਤੱਕ ਕੁਝ ਸਕੈਨ ਨਹੀਂ ਹੋਇਆ',
    'historyEmptyHint': 'ਤੁਹਾਡਾ ਸਕੈਨ ਇਤਿਹਾਸ ਇੱਥੇ ਦਿਖੇਗਾ।',
    'welcomeBack': "ਵਾਪਸੀ 'ਤੇ ਸੁਆਗਤ ਹੈ",
    'signInSubtitle': "ਸਾਰੀਆਂ ਡਿਵਾਈਸਾਂ 'ਤੇ ਆਪਣਾ ਸਕੈਨ ਇਤਿਹਾਸ ਸਿੰਕ ਕਰਨ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।",
    'emailHint': 'ਈਮੇਲ',
    'passwordHint': 'ਪਾਸਵਰਡ',
    'signIn': 'ਸਾਈਨ ਇਨ ਕਰੋ',
    'noAccountSignUp': 'ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ',
    'continueWithoutAccount': 'ਖਾਤੇ ਤੋਂ ਬਿਨਾਂ ਜਾਰੀ ਰੱਖੋ',
    'createAccount': 'ਖਾਤਾ ਬਣਾਓ',
    'signupIntro':
        "ਤੁਹਾਡੇ ਸਕੈਨ ਵੈਸੇ ਵੀ ਇਸ ਡਿਵਾਈਸ 'ਤੇ ਹੀ ਰਹਿੰਦੇ ਹਨ — ਖਾਤਾ ਸਿਰਫ਼ ਉਹਨਾਂ ਨੂੰ ਸਿੰਕ ਅਤੇ ਰਿਕਵਰ ਕਰਨ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ।",
    'organicTreatment': 'ਜੈਵਿਕ ਇਲਾਜ',
    'chemicalTreatment': 'ਰਸਾਇਣਕ ਇਲਾਜ',
    'preventionTips': 'ਰੋਕਥਾਮ ਸੁਝਾਅ',
    'chooseLanguage': 'ਆਪਣੀ ਭਾਸ਼ਾ ਚੁਣੋ',
    'initErrorTitle': 'ਲੀਫਗਾਰਡ ਸ਼ੁਰੂ ਨਹੀਂ ਹੋ ਸਕਿਆ',
    'initErrorBody': 'ਯਕੀਨੀ ਬਣਾਓ ਕਿ ਮਾਡਲ ਫਾਈਲਾਂ ਸਹੀ ਢੰਗ ਨਾਲ ਸੈੱਟ ਕੀਤੀਆਂ ਗਈਆਂ ਹਨ। ਸੈੱਟਅੱਪ ਕਦਮਾਂ ਲਈ ਐਪ ਦੀ README ਵੇਖੋ।',
    'scanLeaf': 'ਪੱਤਾ ਸਕੈਨ ਕਰੋ',
    'diagnoseNow': 'ਹੁਣੇ ਜਾਂਚ ਕਰੋ',

    'settingsTitle': 'ਸੈਟਿੰਗਾਂ',
    'settingsGeneral': 'ਆਮ',
    'settingsAccount': 'ਖਾਤਾ',
    'changeLanguage': 'ਭਾਸ਼ਾ',
    'yourLocation': 'ਤੁਹਾਡਾ ਸਥਾਨ',
    'locationNotSet': 'ਸੈੱਟ ਨਹੀਂ ਹੈ',
    'signedIn': 'ਸਾਈਨ ਇਨ ਹੈ',
    'notSignedInHint': 'ਸਾਰੇ ਡਿਵਾਈਸਾਂ ਤੇ ਆਪਣੇ ਸਕੈਨ ਇਤਿਹਾਸ ਨੂੰ ਸਿੰਕ ਕਰਨ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ।',
    'signOut': 'ਸਾਈਨ ਆਉਟ ਕਰੋ',
    'appVersionLabel': 'ਲੀਫਗਾਰਡ v1.0',

    'setupWelcomeTitle': 'ਲੀਫਗਾਰਡ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
    'setupLanguagePrompt': 'ਉਹ ਭਾਸ਼ਾ ਚੁਣੋ ਜੋ ਤੁਸੀਂ ਵਰਤਣਾ ਚਾਹੁੰਦੇ ਹੋ।',
    'setupLocationTitle': 'ਤੁਸੀਂ ਕਿੱਥੇ ਖੇਤੀ ਕਰਦੇ ਹੋ?',
    'setupLocationPrompt': 'ਇਹ ਤੁਹਾਡੇ ਖੇਤਰ ਅਨੁਸਾਰ ਸਲਾਹ ਦੇਣ ਵਿੱਚ ਮਦਦ ਕਰਦਾ ਹੈ। ਤੁਸੀਂ ਇਸਨੂੰ ਛੱਡ ਕੇ ਬਾਅਦ ਵਿੱਚ ਜੋੜ ਸਕਦੇ ਹੋ।',
    'setupLocationHint': 'ਪਿੰਡ ਜਾਂ ਸ਼ਹਿਰ, ਰਾਜ',
    'continueLabel': 'ਜਾਰੀ ਰੱਖੋ',
    'skipForNow': 'ਹੁਣ ਲਈ ਛੱਡੋ',

    'aiAssistantTitle': 'AI ਸਹਾਇਕ',
    'aiNotConfigured': 'AI ਸਹਾਇਕ ਨੂੰ ਕੰਮ ਕਰਨ ਲਈ ਬੈਕਐਂਡ ਕਨੈਕਸ਼ਨ ਦੀ ਲੋੜ ਹੈ। ਐਪ ਡਿਵੈਲਪਰ ਨੂੰ Supabase ਅਤੇ ai-chat ਫੰਕਸ਼ਨ ਸੈੱਟ ਕਰਨ ਲਈ ਕਹੋ।',
    'askAiCardTitle': 'AI ਸਹਾਇਕ ਨੂੰ ਪੁੱਛੋ',
    'askAiCardSubtitle': 'ਆਪਣੀ ਭਾਸ਼ਾ ਵਿੱਚ ਕਿਸੇ ਵੀ ਫਸਲ ਸਮੱਸਿਆ ਬਾਰੇ ਜਵਾਬ ਪ੍ਰਾਪਤ ਕਰੋ',
    'askAiAboutThis': 'ਇਸ ਬਾਰੇ AI ਨੂੰ ਪੁੱਛੋ',
    'chatWelcomeMessage': 'ਸਤਿ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ ਲੀਫਗਾਰਡ ਦਾ AI ਸਹਾਇਕ ਹਾਂ। ਫਸਲਾਂ ਦੀਆਂ ਬਿਮਾਰੀਆਂ, ਇਲਾਜ ਜਾਂ ਤੁਹਾਡੇ ਪੌਦਿਆਂ ਤੇ ਜੋ ਤੁਸੀਂ ਦੇਖ ਰਹੇ ਹੋ ਉਸ ਬਾਰੇ ਮੈਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ।',
    'chatSeedIssueIntro': 'ਮੈਂ ਦੇਖ ਸਕਦਾ ਹਾਂ ਕਿ ਤੁਹਾਡੇ ਸਕੈਨ ਵਿੱਚ ਸਮੱਸਿਆ ਮਿਲੀ ਹੈ',
    'chatSeedHealthyIntro': 'ਚੰਗੀ ਖ਼ਬਰ — ਤੁਹਾਡਾ ਸਕੈਨ ਸਿਹਤਮੰਦ ਪਾਇਆ ਗਿਆ',
    'chatSeedPrompt': 'ਇਸ ਬਾਰੇ ਮੈਨੂੰ ਕੁਝ ਵੀ ਪੁੱਛੋ — ਕਾਰਨ, ਇਲਾਜ ਦੇ ਵਿਕਲਪ, ਜਾਂ ਇਸਨੂੰ ਫੈਲਣ ਤੋਂ ਕਿਵੇਂ ਰੋਕਿਆ ਜਾਵੇ।',
    'chatInputHint': 'ਆਪਣਾ ਸਵਾਲ ਟਾਈਪ ਕਰੋ…',
    'chatErrorGeneric': 'ਸਹਾਇਕ ਤੱਕ ਨਹੀਂ ਪਹੁੰਚ ਸਕੇ। ਆਪਣਾ ਕਨੈਕਸ਼ਨ ਚੈੱਕ ਕਰੋ ਅਤੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    'chatQuickCause': 'ਇਸਦਾ ਕਾਰਨ ਕੀ ਹੈ?',
    'chatQuickOrganicFirst': 'ਸਭ ਤੋਂ ਸੁਰੱਖਿਅਤ ਜੈਵਿਕ ਹੱਲ ਕੀ ਹੈ?',
    'chatQuickSpreadRisk': 'ਕੀ ਇਹ ਦੂਜੇ ਪੌਦਿਆਂ ਵਿੱਚ ਫੈਲੇਗਾ?',
    'chatQuickKeepHealthy': 'ਮੈਂ ਇਸਨੂੰ ਇਸ ਤਰ੍ਹਾਂ ਸਿਹਤਮੰਦ ਕਿਵੇਂ ਰੱਖਾਂ?',
    'chatQuickPreventFuture': 'ਭਵਿੱਖ ਦੀਆਂ ਸਮੱਸਿਆਵਾਂ ਨੂੰ ਕਿਵੇਂ ਰੋਕਾਂ?',
  };
}
